version: '3.9'
networks:
  expensebook:
    driver: bridge
    name: expensebook
volumes:
  expensebook:
services:
  db:
    image: mysql:8.0.29
    container_name: expensebook-db
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_DATABASE: expensebook
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - expensebook
    volumes:
      - ./database/expensebook.sql:/docker-entrypoint-initdb.d/0_create.sql
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: dockerfile-app
    image: erosvitor/expensebook
    container_name: expensebook-app
    restart: always
    # Estas propriedades sobrepoem as propriedades no 'application.yml'
    environment:
      TZ: America/Sao_Paulo
      DB_URL: jdbc:mysql://db:3308/expensebook?useTimezone=true&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - 8080:8080
    networks:
      - expensebook

